### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by carlosen14** [nathansamson/flutter-builder-docker#4]
do you have any small guide? or where to start from?

**Comment by nathansamson** [comment]
It depends on what you want to achieve.

We have integrated it with Gitlab CI, where our code is checked out in the container, and then we just execute `flutter build apk --debug`, the APK then gets extracted from the container and stored somewhere else

But in essence it should be as simple as
`docker pull nathansamson/flutter-builder-docker
docker run nathansamson/flutter-builder-docker:latest -it -v dir_with_your_code:/app (starts an interactive session)
   cd /app
   flutter build apk --debug (for example)
`

and then your apl should be in dir_with_your_code/build

**Comment by carlosen14** [comment]
nice, i'll take it as a starting point.

have a nice day!!
